import Link from 'next/link'

const publicMotorcycles: Record<string, { bike: string; plate: string; km: string; status: string; history: { date: string; title: string; km: string }[] }> = {
  'RX-004821': { bike: 'Hero Hunk 160 2V', plate: 'ABC123', km: '24.850', status: 'Moto registrada en RODEX', history: [{ date: '04 OCT 2026', title: 'Cambio de aceite e inspección general', km: '24.850 km' }, { date: '18 JUL 2026', title: 'Cambio de aceite y filtro', km: '22.100 km' }] },
}

export default async function PublicRodexPage({ params }: { params: Promise<{ rodexId: string }> }) {
  const { rodexId } = await params
  const moto = publicMotorcycles[rodexId.toUpperCase()] ?? publicMotorcycles['RX-004821']
  return <main className="min-h-screen bg-[#090a0b] px-5 py-8 text-zinc-100 sm:px-8"><div className="mx-auto max-w-2xl"><header className="mb-8 flex items-center justify-between"><div className="text-xl font-black tracking-[0.18em]">RODE<span className="text-[#ed1c24]">X</span></div><span className="text-xs text-zinc-500">Identidad digital de tu motocicleta</span></header><section className="rounded-2xl border border-zinc-800 bg-[#101213] p-6 sm:p-8"><p className="font-mono text-sm font-bold text-[#ed1c24]">RODEX ID</p><h1 className="mt-2 text-3xl font-bold">{rodexId.toUpperCase()}</h1><p className="mt-5 text-xl font-semibold">{moto.bike}</p><div className="mt-1 flex flex-wrap gap-3 text-sm text-zinc-400"><span>{moto.plate}</span><span>·</span><span>{moto.km} km</span></div><div className="mt-5 inline-flex rounded-full border border-emerald-500/25 bg-emerald-500/10 px-3 py-1.5 text-xs text-emerald-400">{moto.status}</div></section><section className="mt-6 rounded-2xl border border-zinc-800 bg-[#101213] p-6"><h2 className="text-lg font-semibold">Historial público</h2><div className="mt-5 space-y-5">{moto.history.map((event) => <article key={event.date} className="border-l-2 border-[#ed1c24] pl-4"><p className="text-xs font-semibold text-[#ed1c24]">{event.date}</p><p className="mt-1 font-medium">{event.title}</p><p className="mt-1 text-xs text-zinc-500">{event.km} · RODEX</p></article>)}</div></section><p className="mt-8 text-center text-xs text-zinc-600">Esta vista no contiene datos personales ni información interna del taller.</p><Link href="/" className="mx-auto mt-4 block w-fit text-xs text-[#ed1c24] hover:underline">Ir al sistema RODEX</Link></div></main>
}
